export {default as Main} from './Main'
export {default as Navbar} from './Navbar'
export {default as PostsDisplay} from './PostsDisplay'
export {default as SinglePost} from './SinglePost'
export {default as Register} from './Register'